### ISSUE TITLE
missing .gitignore, anything else?

### ISSUE THREAD

**Issue by mnyrop** [cul/dlst-studio#5]
@elotroalex looks like we lost the .gitignore when you merged after 81e59c6 (hence all the `.DS_Store` files) Has anything else been acting weird since then? If not I can just re add it.

**Comment by mnyrop** [comment]
note to self to re-add

**Comment by barmintor** [comment]
Looks like this was fixed in https://github.com/cul/dlst-studio/commit/022366ed0beb92a59b3388548119c4fd2fcc5e96
